services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=talentMatcher'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./matchmaker
      dockerfile: Dockerfile
    image: matchmaker-app
    container_name: matchmaker-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/talentMatcher
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    networks:
      - app-network

  frontend:
    build:
      context: ./matchmakerclient
      dockerfile: Dockerfile
    container_name: matchmaker-client
    volumes:
      - ./matchmakerclient:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network: